### ISSUE TITLE
Build fails with HPX 1.4.0

### ISSUE THREAD

**Issue by Sely85** [eth-cscs/DLA-Future#248]
When I try to compile the master branch linking HPX library version 1.4.0, the following error shows up:
```
/home/lara/Documents/DLAF/DLA-Future-trans2stdeigen/src/auxiliary/mc.cpp:5:1:   required from here
/home/lara/installs/hpx-v1.4-release/include/hpx/traits/pack_traversal_rebind_container.hpp:69:12: error: invalid use of incomplete type 'struct hpx::traits::pack_traversal_rebind_container<float, dlaf::common::internal::vector<hpx::lcos::future<float> >, void>'
     struct pack_traversal_rebind_container
```
The problem is fixed when using the next release of HPX (1.4.1). Should we set this latest version as a minimum requirement?

**Comment by albestro** [comment]
I've just built 33226785ae51629930c527f09fa41bcd83a0cdc4 with HPX 1.4.0 on:
- macOS with `Apple LLVM version 10.0.1 (clang-1001.0.46.4)`
- daint with `GCC 8.3.0`

Can you give us more details on your non-working setup, please?

**Comment by Sely85** [comment]
Sure. I'm working on a Linux Mint 19.2 virtual machine with `GCC 7.4.0`.

**Comment by albestro** [comment]
No problem with `GCC 7.3.0`.

Can you try again and share more details? Check that we are talking about the same commit and you don't have any change ongoing. Please attach also the full build output.

**Comment by Sely85** [comment]
Ok! I'm trying to build commit `33226785` as well and the `git status` output is clean, no changes. I attach the output. 

[dlaf-w-hpx1.4.txt](https://github.com/eth-cscs/DLA-Future/files/4824686/dlaf-w-hpx1.4.txt)

**Comment by albestro** [comment]
Just built b6ca22c07a70b421e647bd4c70b869fdc85c70da with GCC 7.5.0, HPX 1.4.0.
So, I'm still not able to replicate the problem.

@Sely85 can you replicate it easily from scratch?

Note: it's just two commits ahead of the reference one, and these two commits are about CI/CD, so they do not change anything for what concerns this issue).

**Comment by Sely85** [comment]
Yes, I have just downloaded the new master, commit `b6ca22c`, and tried to build it again with HPX 1.4.0 and GCC 7.4.0 but I still get the same error.

**Comment by albestro** [comment]
I've built with GCC 7.4.0 without any problem
- boost 1.72.0
- HPX 1.4.0 (using spack, the release commit must be https://github.com/STEllAR-GROUP/hpx/commit/1e2a8410f51b3f399269db5a100098ad1b353f15)
- DLAF b6ca22c07a70b421e647bd4c70b869fdc85c70da

I start thinking it is something in your specific setup. Can you please check thoroughly and share your config?

**Comment by albestro** [comment]
After a quick discussion with @Sely85 , now I'm able to replicate the problem.

The problem is in her configuration, because she was using an HPX commit between releases 1.4.0 and 1.4.1 (specifically https://github.com/STEllAR-GROUP/hpx/commit/8c520f33ba9f066cfe9d53cfeca60a97d8cd54b5).

I'm going to close this issue, since the problem is neither in our library nor in HPX.
