### ISSUE TITLE
Code doesn't compile with g++ 10.2

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#320]
Using g++ 10.2 the code fail to compile due to multiple definition issues.

```
/usr/bin/ld: ../src/libDLAF.a(communicator_grid.cpp.o):(.bss+0x0): multiple definition of `dlaf::to_sizet'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: ../src/libDLAF.a(communicator_grid.cpp.o):(.bss+0x1): multiple definition of `dlaf::to_int'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: ../src/libDLAF.a(communicator_grid.cpp.o):(.bss+0x2): multiple definition of `dlaf::to_SizeType'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x2): first defined here
/usr/bin/ld: ../src/libDLAF.a(tile.cpp.o):(.bss+0x0): multiple definition of `dlaf::to_sizet'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: ../src/libDLAF.a(tile.cpp.o):(.bss+0x1): multiple definition of `dlaf::to_int'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: ../src/libDLAF.a(tile.cpp.o):(.bss+0x2): multiple definition of `dlaf::to_SizeType'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x2): first defined here
/usr/bin/ld: ../src/libDLAF.a(matrix.cpp.o):(.bss+0x0): multiple definition of `dlaf::to_sizet'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: ../src/libDLAF.a(matrix.cpp.o):(.bss+0x1): multiple definition of `dlaf::to_int'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: ../src/libDLAF.a(matrix.cpp.o):(.bss+0x2): multiple definition of `dlaf::to_SizeType'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x2): first defined here
/usr/bin/ld: ../src/libDLAF.a(mc.cpp.o):(.bss+0x0): multiple definition of `dlaf::to_sizet'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: ../src/libDLAF.a(mc.cpp.o):(.bss+0x1): multiple definition of `dlaf::to_int'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: ../src/libDLAF.a(mc.cpp.o):(.bss+0x2): multiple definition of `dlaf::to_SizeType'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x2): first defined here
/usr/bin/ld: ../src/libDLAF.a(distribution.cpp.o):(.bss+0x0): multiple definition of `dlaf::to_sizet'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: ../src/libDLAF.a(distribution.cpp.o):(.bss+0x1): multiple definition of `dlaf::to_int'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: ../src/libDLAF.a(distribution.cpp.o):(.bss+0x2): multiple definition of `dlaf::to_SizeType'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x2): first defined here
/usr/bin/ld: ../src/libDLAF.a(layout_info.cpp.o):(.bss+0x0): multiple definition of `dlaf::to_sizet'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x0): first defined here
/usr/bin/ld: ../src/libDLAF.a(layout_info.cpp.o):(.bss+0x1): multiple definition of `dlaf::to_int'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x1): first defined here
/usr/bin/ld: ../src/libDLAF.a(layout_info.cpp.o):(.bss+0x2): multiple definition of `dlaf::to_SizeType'; CMakeFiles/miniapp_triangular_solver.dir/miniapp_triangular_solver.cpp.o:(.bss+0x2): first defined here
```
Which are referred to these lambda functions:
[https://github.com/eth-cscs/DLA-Future/blob/master/include/dlaf/types.h#L155-L171](https://github.com/eth-cscs/DLA-Future/blob/master/include/dlaf/types.h#L155-L171)

I reduced the problem to the following minimal example which works with clang++ 8.0, 9.0, 10.0 and g++ 8.4 and 9.3, but doesn't with gcc 10.2:
```
<a.h>
auto f = [](){return 0;};

int a();
```

```
<a.cpp>
#include "a.h"

int a() {
  return f();
}
```

```
<main.cpp>
#include<iostream>
#include "a.h"

int main() {
  std::cout << f() << std::endl;
  std::cout << a() << std::endl;
}
```

**Comment by albestro** [comment]
I started investigating a bit with a similar code (mainly without `iostream`, to avoid having too many symbols).

```
$ cat a.h
auto mylambda = [](){return 0;};
$ cat a.cpp
#include "a.h"
$ cat aa.cpp
#include "a.h"
int main() {
  mylambda();
}
```

GCC 10
```
$ gcc --version
gcc (GCC) 10.2.0 20200723 (Cray Inc.)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ make
CC -c a.cpp
nm --demangle a.o
0000000000000000 B mylambda
CC -c aa.cpp
nm --demangle aa.o
0000000000000000 T main
0000000000000000 B mylambda
0000000000000000 W mylambda::{lambda()#1}::operator()() const
CC a.o aa.o
/usr/bin/ld: aa.o:(.bss+0x0): multiple definition of `mylambda'; a.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:6: all] Error 1
```

GCC 9
```
$ gcc --version
gcc (GCC) 9.3.0 20200312 (Cray Inc.)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ make
CC -c a.cpp
nm --demangle a.o
0000000000000000 b mylambda
CC -c aa.cpp
nm --demangle aa.o
000000000000000f T main
0000000000000000 b mylambda
0000000000000000 t {lambda()#1}::operator()() const
CC a.o aa.o
```

The main difference, as expected, is that the two different versions expose the symbol `mylambda` differently, GCC 10 with external linkage (uppercase `B`) and GCC 9 with internal linkage (lowercase `b`).

IMHO it looks correct the behavior of GCC 10, and it is quite strange that no other compiler ever exposed the bug.

Waiting for more authoritative feedback!

**Comment by teonnik** [comment]
I can't reproduce the bug. The following spack DLA-F spec with gcc@10.2 builds fine `spack install dla-future %gcc ^blaspp -cuda ^hpx@1.5.0 +async_mpi instrumentation=apex ^mpich`:

```
[+]  pvcne5s  dla-future@develop%gcc@10.2.0~cuda~doc~ipo~miniapps build_type=RelWithDebInfo cuda_arch=none arch=linux-arch-skylake
[+]  wfeegw6      ^blaspp@2020.10.02%gcc@10.2.0~cuda~ipo+openmp+shared build_type=RelWithDebInfo cuda_arch=none arch=linux-arch-skylake
 -   sqefjsj          ^cmake@3.19.3%gcc@10.2.0~doc+ncurses+openssl+ownlibs~qt arch=linux-arch-skylake
[+]  vengwtb          ^intel-mkl@2020.4.304%gcc@10.2.0~ilp64+shared threads=none arch=linux-arch-skylake
 -   aifsvza              ^cpio@2.13%gcc@10.2.0 patches=d22633c368b8aedf4c08b23b6fbaa81a52404c8943ab04926404083ac10f1a4b arch=linux-arch-skylake
[+]  unf5ao5      ^hpx@1.5.0%gcc@10.2.0~async_cuda+async_mpi~cuda~examples~generic_coroutines~ipo~tools build_type=RelWithDebInfo cuda_arch=none cxxstd=14 instrumentation=apex malloc=tcmalloc max_cpu_count=64 networking=none arch=linux-arch-skylake
[+]  pnry464          ^boost@1.75.0%gcc@10.2.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=14 visibility=hidden arch=linux-arch-skylake
[+]  42n3fqo              ^bzip2@1.0.8%gcc@10.2.0+shared arch=linux-arch-skylake
[+]  f266p5g              ^zlib@1.2.11%gcc@10.2.0+optimize+pic+shared arch=linux-arch-skylake
 -   qubpnwn          ^git@2.30.0%gcc@10.2.0~svn+tcltk arch=linux-arch-skylake
[+]  3m4fdnh          ^gperftools@2.7%gcc@10.2.0 arch=linux-arch-skylake
[+]  4bwevyd              ^libunwind@1.4.0%gcc@10.2.0~pic~xz~zlib arch=linux-arch-skylake
[+]  clem3d4          ^hwloc@2.4.0%gcc@10.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-arch-skylake
[+]  7sjc4o7              ^libpciaccess@0.16%gcc@10.2.0 arch=linux-arch-skylake
[+]  4uvyydw              ^libxml2@2.9.10%gcc@10.2.0~python arch=linux-arch-skylake
[+]  wwe5akp              ^pkgconf@1.7.3%gcc@10.2.0 arch=linux-arch-skylake
[+]  ducdyvm          ^mpich@3.4.1%gcc@10.2.0~argobots+fortran+hwloc+hydra+libxml2+pci+romio~slurm~verbs+wrapperrpath device=ch4 netmod=ofi pmi=pmi arch=linux-arch-skylake
 -   3h2c4xg              ^findutils@4.7.0%gcc@10.2.0 arch=linux-arch-skylake
[+]  65peojr              ^libfabric@1.11.0%gcc@10.2.0~kdreg fabrics=sockets,tcp,udp arch=linux-arch-skylake
[+]  e452g6d          ^otf2@2.2%gcc@10.2.0 arch=linux-arch-skylake
[+]  wuijoid          ^python@3.9.1%gcc@10.2.0+bz2+ctypes+dbm~debug+libxml2+lzma+nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-arch-skylake
[+]  txa5qvr      ^lapackpp@2020.10.02%gcc@10.2.0~ipo+shared build_type=RelWithDebInfo arch=linux-arch-skylake

```

**Comment by albestro** [comment]
We may have a fix for that, e.g. by specifying the linkage, but I'm waiting for some more authoritative feedback since it seems there is a particularity in the C++ standard.
