### ISSUE TITLE
Build error in case DLAF_ASSERTs are disabled

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#1333]
The problem is introduced by #1321 with

https://github.com/eth-cscs/DLA-Future/blob/09ac239f32e1dd88776d14b64d7a7442dd56addf/include/dlaf/matrix/matrix.h#L97-L99

where the `DLAF_ASSERT` is used to check the correct size of the `initializer_list` with a comma operator.

Disabling `DLAF_ASSERT` makes them "empty" expressions, making the comma operator complaining that the first operand is missing.

```
In constructor 'dlaf::matrix::Matrix<T, D>::Matrix(std::initializer_list<long int>, const dlaf::TileElementSize&, dlaf::matrix::MatrixAllocation, dlaf::matrix::LdSpec)':
/capstor/store/cscs/cscs/csstaff/ialberto/workspace/dla-future.master/include/dlaf/matrix/matrix.h:97:65: error: expected primary-expression before ',' token
   97 |       : Matrix<T, D>((DLAF_ASSERT(size.size() == 2, size.size()),
      |                                                                 ^
```

The fix for this might be opinionated, so I opted for opening an issue instead of a PR with one of the possible changes.
